### PR TITLE
fix grammar: "is a not a"

### PR DESCRIPTION
**Pull request by michaelficarra**

### CODE REVIEW

**Comment by annevk** [comment]
Thanks for the fix, could you please read and see if you can sign https://participate.whatwg.org/agreement?

Also, please add your name to the Acknowledgments section (either here or the other PR).

**Comment by michaelficarra** [comment]
@annevk I'm still waiting on verification.

**Comment by domenic** [comment]
I went to verify, but I realized that since Shape Security is in the field of web technologies, you cannot sign as an individual; you need to sign as an entity.

**Comment by annevk** [comment]
@michaelficarra any update here?

**Comment by michaelficarra** [comment]
@annevk I've pinged our legal department about getting the participation agreement signed again. Thanks for the reminder.

**Comment by annevk** [comment]
@michaelficarra any progress here?

**Pull request closed without merging**
