### PR TITLE
Editorial: Fix CORS legal and illegal combinations table

### PR DESCRIPTION
**Pull request by anssiko**
***
<a href="https://whatpr.org/fetch/1115.html" title="Last updated on Jan 15, 2021, 7:39 AM UTC (296fb0f)">Preview</a> | <a href="https://whatpr.org/fetch/1115/c5f8177...296fb0f.html" title="Last updated on Jan 15, 2021, 7:39 AM UTC (296fb0f)">Diff</a>

### CODE REVIEW

**Review by annevk — COMMENTED** [review]
This does not look correct to me. The reason sharing fails is because it has a trailing slash. The reason sharing works in the second example is because it does not have a trailing slash.

**Comment by anssiko** [comment]
Thanks for your swift review. I was confused.

If I'd like to propose "serialized" to be linked to its canonical definition to clarify this table, where should I look at?

**Comment by anssiko** [comment]
@annevk I suspect I should have looked at https://html.spec.whatwg.org/multipage/origin.html#ascii-serialisation-of-an-origin

PR updated accordingly, PTAL.

**Review by annevk — APPROVED** [review]

**Comment by annevk** [comment]
Hey @anssiko this looks good, but you'll have to amend entities.json in https://github.com/whatwg/participant-data to indicate Intel also wishes to participate in the Fetch Workstream.

**Comment by anssiko** [comment]
@annevk thanks, let me get that detail sorted out.

**Comment by anssiko** [comment]
@annevk PTAL https://github.com/whatwg/participant-data/pull/32

Sorry for the delay, paperwork can take its time...

**Comment by annevk** [comment]
Thanks @anssiko!

**Comment by anssiko** [comment]
Thanks @annevk! Let this pave the way for possible more substantial contributions in the future. Our folks have done work on Blink bindings as well as fixed interop bugs in Chromium motivated by Fetch spec. Now, can also contribute spec fixes and clarifications as needed.

**Pull request merged**
