### PR TITLE
CI test

### PR DESCRIPTION
**Pull request by annevk**
***
<a href="https://whatpr.org/fetch/1605.html" title="Last updated on Feb 16, 2023, 4:15 PM UTC (f7ad391)">Preview</a> | <a href="https://whatpr.org/fetch/1605/bc97a85...f7ad391.html" title="Last updated on Feb 16, 2023, 4:15 PM UTC (f7ad391)">Diff</a>

### CODE REVIEW

**Comment by saschanaz** [comment]
It seems https://github.com/speced/bikeshed/issues/2471 tracks this.

**Comment by annevk** [comment]
Thanks for finding that! It seems there are some network failures too. I guess we have to wait a bit.

**Comment by tabatkins** [comment]
Should be good now, kick this and verify?

**Comment by saschanaz** [comment]
Retried in #1593 with no luck 🤔, maybe there's some cache? Could be useful if the deploy script showed the bikeshed version it's using.

**Comment by tabatkins** [comment]
Aaaaaaah, the release I made this morning fails because it is missing some newly-created CSS files from another commit, so it's just dying for an unrelated reason.

I've run into this issue before, so I looked more into it and think I've fixed it permanently. Version 3.11.8 is up and should be good now.

**Comment by saschanaz** [comment]
CSSWG now has the CSS-faulted version, I guess we should wait a bit more then!

**Comment by tabatkins** [comment]
Yeah, it'll update in a few minutes; I'm not sure if it's got some hook from pypi or just runs on a cron.

**Comment by annevk** [comment]
Well, getting closer but no cigar: https://github.com/speced/bikeshed/issues/2476.

**Pull request closed without merging**
