### PR TITLE
Hard-code `localhost` to loopback addresses.

### PR DESCRIPTION
**Pull request by mikewest**
This patch incorporates draft-ietf-dnsop-let-localhost-be-localhost's recommendation
to hard-code resolution of `*.localhost` domains to 127.0.0.1 and [::1], matching
the existing behavior of both Chrome and Firefox. This change allows user agents
to ensure that localhost contexts meet the secure context requirements laid out
in https://w3c.github.io/webappsec-secure-contexts/#localhost.

See https://datatracker.ietf.org/doc/html/draft-ietf-dnsop-let-localhost-be-localhost
for additional detail and justification.

- [X] At least two implementers are interested (and none opposed):
   * Chrome ships this mapping.
   * Firefox does as well.
- [ ] [Tests](https://github.com/web-platform-tests/wpt) are written and can be reviewed and commented upon at:
   * I don't think we can test this via WPT, as we can't ensure that a server is running on loopback addresses on the machine from which tests are being executed.
- [X] [Implementation bugs](https://github.com/whatwg/meta/blob/main/MAINTAINERS.md#handling-pull-requests) are filed:
   * Chrome: https://crbug.com/691930
   * Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1220810
   * Safari: https://bugs.webkit.org/show_bug.cgi?id=171934

(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)

***
<a href="https://whatpr.org/fetch/1257.html" title="Last updated on Jun 22, 2021, 12:28 PM UTC (b13ccf2)">Preview</a> | <a href="https://whatpr.org/fetch/1257/0cee83d...b13ccf2.html" title="Last updated on Jun 22, 2021, 12:28 PM UTC (b13ccf2)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
I pushed some nits. In particular I made the IPv6 address go first and used the notation without square brackets as that is reserved for inside URLs.

(This would fix #1118.)

**Comment by annevk** [comment]
cc @fred-wang

**Comment by mikewest** [comment]
Your nit fixes LGTM. Thanks!

**Comment by ricea** [comment]
lgtm

**Review by ricea — APPROVED** [review]

**Pull request merged**
