### PR TITLE
Set final connection timing info after failure check

### PR DESCRIPTION
**Pull request by annevk**
@noamr @yoavweiss could you review?

***
<a href="https://whatpr.org/fetch/1248.html" title="Last updated on Jun 3, 2021, 1:57 PM UTC (2a7e355)">Preview</a> | <a href="https://whatpr.org/fetch/1248/43a0c94...2a7e355.html" title="Last updated on Jun 3, 2021, 1:57 PM UTC (2a7e355)">Diff</a>

### CODE REVIEW

**Comment by yoavweiss** [comment]
Seems reasonable. IIUC, this would means that we drop all connection time reporting in case of a network error. Is that correct? Would this resolve https://github.com/whatwg/fetch/issues/1215 or is there more work involved?

We'd also want to add related tests, or at least keep track of the fact we need to add ones.

**Comment by annevk** [comment]
No, doing things accurately for network errors is an outstanding issue still. This just fixes an existing problem whereby it tries to obtain final connection timing info from a failure value (i.e., not a connection).

**Review by yoavweiss — APPROVED** [review]
LGTM

**Comment by yoavweiss** [comment]
> No, doing things accurately for network errors is an outstanding issue still. This just fixes an existing problem whereby it tries to obtain final connection timing info from a failure value (i.e., not a connection).

OK, that makes sense!

**Pull request merged**
