### PR TITLE
CORS preflights need a service-workers mode of "none"

### LINKED ISSUE #558: Should CORS preflight fetch also copy request's service-workers mode?
https://fetch.spec.whatwg.org/commit-snapshots/f3bb21991abdd335175fcc5d26a0d0b7b380d4fe/#cors-preflight-fetch

> Let preflight be a new request whose method is \`OPTIONS\`, url is request’s current url, initiator is request’s initiator, type is request’s type, destination is request’s destination, origin is request’s origin, referrer is request’s referrer, and referrer policy is request’s referrer policy\.

_preflight_ does not seem to have copied _request_'s service-workers mode. Should it do so?

### PR DESCRIPTION
**Pull request by annevk**
Fixes #558.

This probably does not matter as it's never going to be same-origin, but better safe than sorry.

***
[Preview](https://fetch.spec.whatwg.org/branch-snapshots/annevk/preflight-service-workers-mode/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fetch/bc23529...7830c74.html)

### CODE REVIEW

**Comment by annevk** [comment]
It does actually matter I just realized. You can go cross-origin and then same-origin via a redirect.

**Comment by jakearchibald** [comment]
I don't think this is technically needed because **CORS-preflight fetch** calls **HTTP-network-or-cache fetch**, whereas the service worker interception happens in **HTTP fetch**.

Redirects aren't an issue, because **HTTP-network-or-cache fetch** doesn't follow redirects. Well, it's an issue if CORS preflights are expected to follow redirects. Are they?

Setting this for safety seems fine, but maybe include a note to say it doesn't do anything right now?

**Comment by annevk** [comment]
No, a CORS preflight itself doesn't follow redirects. But the actual request following it will (resulting in another CORS preflight for the new URL).

So given that, I think it would be better to point out your finding in a note than add this. That makes it much more clear what's going on.

**Comment by annevk** [comment]
Okay, should be good now.

**Pull request merged**
