### PR TITLE
Editorial: Fix implementation-defined links

### PR DESCRIPTION
**Pull request by dlrobertson**
Related to: #1580

***
<a href="https://whatpr.org/fetch/1581.html" title="Last updated on Jan 2, 2023, 6:54 PM UTC (88c8ca2)">Preview</a> | <a href="https://whatpr.org/fetch/1581/464326e...88c8ca2.html" title="Last updated on Jan 2, 2023, 6:54 PM UTC (88c8ca2)">Diff</a>

### CODE REVIEW

**Comment by domenic** [comment]
Why not use link-defaults like the error message suggests?

**Comment by dlrobertson** [comment]
> Why not use link-defaults like the error message suggests?

I didn't see another one in this spec, but that probably makes sense

**Comment by dlrobertson** [comment]
Updated to use a `link-defaults` block

**Comment by dlrobertson** [comment]
Updated to only specify the default for `implementation-defined` after the webdriver spec was fixed.

**Pull request merged**
