### PR TITLE
Simplify HeadersInit

### PR DESCRIPTION
**Pull request by annevk**
Since Headers has an iterator now through its iterable<> declaration
there’s no real need to special case.

It might be slightly faster to have it there, but this is not
performance-critical code and I’d rather have it be simple.

### CODE REVIEW

**Comment by annevk** [comment]
@bzbarsky @wanderview @domenic thoughts?

**Comment by wanderview** [comment]
Does this have any change on behavior visible to script?  If not, then I I have no objections.

**Comment by annevk** [comment]
It does. If you overwrite the iterator of a Headers object that would be invoked instead by the binding layer.

**Comment by bzbarsky** [comment]
Right, the behavior also changes if people have messed with array iterators (so the inner sequence produces unexpected values).

It's probably OK to not worry about those edge cases.

**Comment by domenic** [comment]
Looks good; tests would probably help.

**Comment by annevk** [comment]
I created https://github.com/w3c/web-platform-tests/pull/4240. It seems we already had many tests for IDL records since everyone implemented that somehow before IDL got them.

**Comment by annevk** [comment]
Tests landed. Waiting with landing this until a Shepherd issue is resolved.

**Pull request merged**
