### PR TITLE
Added manifest-src directive to request rel. table

### PR DESCRIPTION
**Pull request by marcoscaceres**
Defined here: https://w3c.github.io/webappsec/specs/content-security-policy/#manifest_src

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Wait, it wasn't merged. It's just a PR.

**Comment by annevk** [comment]
I see, but we ended up with a tweet because it was a commit on whatwg/fetch. I guess that should only follow master. Sorry.

**Comment by domenic** [comment]
Yeah, I had to bug GitHub to add an option to the tweeter thingy so that it only follows master. Probably worth enabling on all whatwg repos now that it exists.

**Comment by annevk** [comment]
I've added "master" to Filter in most places now.

**Pull request closed without merging**
