### PR TITLE
Use UTF-8 decode without BOM for multipart/form-data

### LINKED ISSUE #650: Should Body.formData() always strip the BOM?
This came up in https://bugs.chromium.org/p/chromium/issues/detail?id=796192. Blink's currently failing some of the tests added in https://github.com/w3c/web-platform-tests/pull/4517 due to multiple issues.

The `\uFEFFtest=\uFEFF` tests, specifically, fail with `Request` and `Response` because the leading `\uFEFF` ends up being stripped when `Body.formData()` is called.

The input string is correctly [parsed as a USVString and encoded in UTF-8](https://fetch.spec.whatwg.org/#body-mixin) as `\xef\xbb\xbftest=\xef\xbb\xbf`, and calling `Body.formData()` with `Content-Type: application/x-www-form-urlencoded` causes it to be [parsed](https://url.spec.whatwg.org/#urlencoded-parsing) and the string to be decoded via [UTF-8 decode without BOM](https://encoding.spec.whatwg.org/#utf-8-decode-without-bom).

Calling `Body.json()` and `Body.text()`, however, decodes the same UTF-8 string with [UTF-8 decode](https://encoding.spec.whatwg.org/#utf-8-decode), which does strip the BOM from the beginning when it's present.

I was wondering if this "asymmetry" is intentional, or whether we should be using the same decoding algorithm for all functions mentioned above.

### PR DESCRIPTION
**Pull request by annevk**
Tests: https://github.com/web-platform-tests/wpt/pull/17589?

Closes #650.

***
<a href="https://whatpr.org/fetch/915.html" title="Last updated on Jul 2, 2019, 12:38 PM UTC (ba239a1)">Preview</a> | <a href="https://whatpr.org/fetch/915/cc80ec5...ba239a1.html" title="Last updated on Jul 2, 2019, 12:38 PM UTC (ba239a1)">Diff</a>

### CODE REVIEW

**Comment by kunal6673** [comment]
Start

**Comment by annevk** [comment]
@hiroshige-g does this look good? Any updates on the tests?

**Comment by hiroshige-g** [comment]
Note:
This PR aligns with Firefox.
Chromium will follow (https://chromium-review.googlesource.com/c/chromium/src/+/1796367/).
The test failing on Safari.

**Comment by annevk** [comment]
Filed https://bugs.webkit.org/show_bug.cgi?id=203808 on WebKit.

**Pull request merged**
