### PR TITLE
Editorial: spell cypher as cipher

### PR DESCRIPTION
**Pull request by foolip**
Matches https://w3c.github.io/webcrypto/Overview.html.

***
<a href="https://whatpr.org/fetch/649.html" title="Last updated on Dec 20, 2017, 9:44 AM GMT (aa87e33)">Preview</a> | <a href="https://whatpr.org/fetch/649/4c0227b...aa87e33.html" title="Last updated on Dec 20, 2017, 9:44 AM GMT (aa87e33)">Diff</a>

### CODE REVIEW

**Comment by foolip** [comment]
I went look for a typo to see how Travis would behave with the recent changes, and this is the best I could find :)

**Comment by annevk** [comment]
Interesting, there seem to be slightly more results for cipher and https://english.stackexchange.com/questions/147965/cipher-vs-cypher also backs you up somewhat. Added to https://wiki.whatwg.org/wiki/Style#Dictionary.

**Comment by foolip** [comment]
https://travis-ci.org/whatwg/fetch/builds/319083811 was the only Travis build spawned by this (before merging) so it all seems to be working.

**Comment by annevk** [comment]
Follow-up: https://github.com/whatwg/html/pull/3307.

**Pull request merged**
