### PR TITLE
Adding bikeshed metadata to Methods, Headers, Statuses, and Bodies.

### PR DESCRIPTION
**Pull request by mikewest**
tabatkins/bikeshed#773

@annevk: How do you feel about this terribly exciting patch? I figure we can add the bits and pieces in a few patches rather than trying to do it all at once.

@tabatkins: FYI. Doing a quick comparison between the generated doc here and some other Bikeshed-generated docs, this looks like it'll work. Fingers crossed...

### CODE REVIEW

**Comment by annevk** [comment]
This looks pretty reasonable, but I have the feeling you didn't always pay attention to the 100 column width. I can clean that up I suppose.

**Comment by mikewest** [comment]
Latest patch is locked to 100 columns.

**Comment by mikewest** [comment]
(For the lines I touched; I didn't fix the whole file)

**Comment by annevk** [comment]
Landed as https://github.com/whatwg/fetch/commit/d45421ae19fde7888a015c1ae02d36ff4fd2f460.

**Comment by annevk** [comment]
Thanks!

**Pull request closed without merging**
