### PR TITLE
Fixup the request destination table values 

### PR DESCRIPTION
**Pull request by yoavweiss**
The request destination table got broken in https://github.com/whatwg/fetch/commit/6b9cdaa9be7acd2b8074c74823981ef994d17857

This fixes that table.

### CODE REVIEW

**Comment by annevk** [comment]
I think what should happen instead is that 15 should become 16 and 5 should become 6 for rowspan. @igrigorik had that correct after all and I'm not sure why I thought I knew better. 😟

**Comment by annevk** [comment]
(Because "embed" is not a type and "video" is not an initiator.)

**Comment by igrigorik** [comment]
Yep, looks like the embed and video rows need to be shifted right by 1 :)

**Comment by annevk** [comment]
Can you change Overview.src.html too @yoavweiss? I'm happy to generate Overview.html from it, up to you.

**Comment by yoavweiss** [comment]
@annevk - added the Overview.src.html file (and removed the Overview.html)

**Comment by annevk** [comment]
Committed as https://github.com/whatwg/fetch/commit/b18594b356ebe2a87602a66eb77ad3d80f3250dd. Also added you to the acknowledgments section, since you weren't there yet surprisingly enough!

**Pull request closed without merging**
