### PR TITLE
Editorial: rename keepalive flag to keepalive

### PR DESCRIPTION
**Pull request by annevk**
This simplifies some algorithms and helps with #954.

***
<a href="https://whatpr.org/fetch/1152.html" title="Last updated on Feb 2, 2021, 2:20 PM UTC (a75ffa6)">Preview</a> | <a href="https://whatpr.org/fetch/1152/987c3fd...a75ffa6.html" title="Last updated on Feb 2, 2021, 2:20 PM UTC (a75ffa6)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
@yoichio is the second commit here what you had in mind?

**Comment by yoichio** [comment]
LGTM for me to fix #1061.

**Comment by annevk** [comment]
Thanks @yoichio! Does the variable name refactoring help with #954?

**Comment by yoichio** [comment]
Yes, but I have 2 requests.
1. Use `inputOrInitBody`  and `InitBody` rather than `ExtractedBody` to emphasize the later comes from `input`.
2. Avoid using `extractedBody` at the step 41 after introducing `inputOrExtractedBody` because it is "consumed". How about move this step into 38?

**Comment by annevk** [comment]
We cannot move all of 41 to 38 as that would move a step that should happen after all throwing, before some of the throwing. I will look into the names though.

**Comment by annevk** [comment]
@yoichio if you could take another look that'd be great.

**Comment by yoichio** [comment]
Thanks. LGTM.

**Pull request merged**
