### PR TITLE
Add device-memory and network quality client hints to the list

### PR DESCRIPTION
**Pull request by tarunban**
annevk: please take a look. This is the first PR where the new client hints are added to the spec.

***
<a href="https://whatpr.org/fetch/725.html" title="Last updated on May 30, 2018, 11:54 PM GMT (43eea2f)">Preview</a> | <a href="https://whatpr.org/fetch/725/3055f13...43eea2f.html" title="Last updated on May 30, 2018, 11:54 PM GMT (43eea2f)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
This doesn't seem to ever set them in the request?

Also, I think we should start by fixing the architecture for what's there now first. Otherwise it'd be rather hard to write tests and such.

**Comment by annevk** [comment]
And also, thanks for your pull request! And please add your name to the Acknowledgments section (unless you don't want to).

**Comment by tarunban** [comment]
annevk: I am working on fixing the architecture in the spec, but that's taking a bit longer. I thought I would get this out first. Since my blink-dev i2s requires all this yak shaving anyways, I am not sure if the order is super critical? Please let me know. Thanks!

**Comment by annevk** [comment]
@tarunban https://whatwg.org/working-mode#changes might help. We have a pretty high bar for changes these days. So apart from these additions, we'll also need tests and the tests need to be based on the specification. And at that point you need the infrastructure in place.

**Comment by annevk** [comment]
Closing per 6a644c676558edc7e80548e25c6f85bf0143f395.

**Pull request closed without merging**
