### PR TITLE
Editorial: Remove a duplicate "in"

### PR DESCRIPTION
**Pull request by nico**
***
<a href="https://whatpr.org/fetch/1528.html" title="Last updated on Nov 3, 2022, 5:39 PM UTC (b970453)">Preview</a> | <a href="https://whatpr.org/fetch/1528/154061f...b970453.html" title="Last updated on Nov 3, 2022, 5:39 PM UTC (b970453)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
Assuming you're with Google you need to make your membership of the googlers GitHub organization public to satisfy the IPR bot.

**Comment by nico** [comment]
How do I do that?

And, do I have to? It's not like this is a terribly involved change, and non-Googlers seem to be able to have PRs changed as well.

**Comment by nico** [comment]
(Also, thanks for the quick reply!)

**Comment by annevk** [comment]
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership

Everyone that contributes has to sign https://participate.whatwg.org/agreement one way or another. If you're part of an organization it goes through GitHub organizations, essentially.

The WHATWG Steering Group is working on making it easier to accept changes such as this one, but as of yet that's still unresolved unfortunately.

**Comment by nico** [comment]
Hm, looks like I can't sign that as an individual since I _do_ "work in the field of web technologies as an employee", but I'd also prefer not to publicly advertise my employment via https://github.com/googlers (not that it's terribly hidden, but still). Hopefully someone else can independently rediscover this typo!

**Pull request closed without merging**
